//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.15 at 10:18:06 AM GMT 
//
package is.hi.torg.vinnsla;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * @author Sigríður Ösp sos42@hi.is
 * Stillir deck listann í Decks.xml
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "decks"
})
@XmlRootElement(name = "root")
public class Root {
    @XmlElement(name = "deck", required = true)
    protected List<Deck> decks;

    public List<Deck> getDecks() {
        if (decks == null) {
            decks = new ArrayList<Deck>();
        }
        return decks;
    }
}
